### PR TITLE
Set required version to 0.6.0

### PR DESCRIPTION
**Pull request by tpadioleau**

### CODE REVIEW

**Review by jbigot — DISMISSED** [review]
Maybe you can be slightly less strict about version and accept a range for patch versions?

**Comment by tpadioleau** [comment]
Like `0.6...<0.7` ?

**Comment by jbigot** [comment]
> Like `0.6...<0.7` ?

Yes, I believe this is also equivalent to just `0.6 EXACT`, no?

**Comment by tpadioleau** [comment]
It does not seem to work, tried with `find_package(Ginkgo 1.7 EXACT REQUIRED)` though version `1.7.0` is available.

**Comment by tpadioleau** [comment]
Cmake supports ranges only from version 3.19, Ubuntu focal seems to use 3.16.

**Comment by tpadioleau** [comment]
Merging, feel free to reopen the issue if you have a better option

**Pull request merged**
