### PR TITLE
ac/ddc std algos: add label on parallel_for_each

### PR DESCRIPTION
**Pull request by acalloo**

### CODE REVIEW

**Comment by tpadioleau** [comment]
@acalloo Is it ready to review ? If so can you please undraft it and rebase on `main` ?

**Comment by acalloo** [comment]
Forgot to do that, sorry. Done, and ready for review. Had a conflict because of the README.md which I solved. Should be ok now.

**Review by tpadioleau — APPROVED** [review]
Yep looks good to me, thanks!

**Comment by acalloo** [comment]
Great! Sorry for having been long on that, was taken up elsewhere.

**Pull request merged**
